config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :orders
  resources :shopping_lists, only: [:index, :show, :create]
  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord

  after_create :add_products
  has_one :product_list
  has_many :products
  belongs_to :shopping_list, optional: true, dependent: :destroy

  accepts_nested_attributes_for :products

  private

   def add_products
     base_products = Product.base_products

     base_products.each do |product|
       if product.order_today?
         attrs = product.attributes.except('id')
         attrs['base_product'] = false
         self.products.create(attrs)
       end
     end
   end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :order, optional: true

  scope :base_products, -> { where(base_product: true) }

  def order_today?
    return true if (self.days_to_order.include?(Time.now.strftime("%A")) || self.days_to_order.include?("Everyday") )
  end
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  
end

app/models/shopping_item.rb
class ShoppingItem < ApplicationRecord

  belongs_to :shopping_list

  scope :need_to_order, -> { where(need_to_order: true) }

  def set_shopping_item_attributes(product)
    self.item_name = product.name
    self.item_cost = product.price
    self.item_amount = (product.desired_total - product.in_stock).ceil
    self.total_cost = self.item_amount * self.item_cost
    self.need_to_order = product.in_stock <= product.theshold_to_order ? true : false
  end

end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  has_one :order
  has_many :shopping_items

  def all_shopping_items
    self.shopping_items
  end

  def items_needed_to_order
    all_shopping_items.need_to_order
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_locale
  protect_from_forgery with: :exception

  def set_locale
      I18n.locale = params[:locale]
  end

  def current_order
    Order.find(session[:current_order_id])
  end

  def default_url_options(options = {})
    { locale: I18n.locale }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
  end

  def index
    @orders = Order.all
    @shopping_lists = []
    @was_created = false

    @orders.each do |order|
      @shopping_list = ShoppingList.find_or_create_by(order_id: order.id) do |s|
        @was_created = true
      end

      order.products.each_with_index do |p,idx|
        item = nil
        if @was_created
          # shopping list creation date should be same as order!
          @shopping_list.update_attributes(created_at: order.created_at)
          item = @shopping_list.shopping_items.build
        else
          item = @shopping_list.shopping_items[idx]
        end
        if !item.nil?
          item.set_shopping_item_attributes(p)
          if item.save
            # no problems
            item.update_attributes(shopping_list_id: @shopping_list.id)
          else
            raise "Error saving item: #{item.inspect}"
          end
        end
        #@shopping_items.push(@shopping_list.items_needed_to_order)
      end
      @shopping_lists.push(@shopping_list)
    end

    @lists = Kaminari.paginate_array(@shopping_lists.sort_by {
      |i| i.created_at
    }.reverse).page(params[:page]).per(5)
  end

  def new
    @order = Order.create!
    session[:current_order_id] = @order.id
    @products = @order.products
    redirect_to @order
  end

  def update
    @order = Order.find(params[:id])

    (0...total_order_products).each do |idx|
      params[:order][:products_attributes][idx.to_s].each do |k,v|
        @order.products[idx].update_attribute(k, v) unless k == 'id'
      end
    end

    flash[:success] = "Order updated!"
    redirect_to @order
  end

  def show
    @order = Order.find(params[:id])
    @order_products = []
    @order.products.each do |p|
      if p.order_today?
        @order_products.push(p)
      end
    end

    @shopping_list = ShoppingList.new
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    flash[:success] = "Order remove from system."
    redirect_to :back
  end

  private

  def total_order_products
    if !params[:order].nil?
      params[:order][:products_attributes].size
    else
      return 0
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def create
    @product = Product.new(product_params)

    if @product.save
      @product.update_attributes(base_product: true)
      @product.update_attributes(days_to_order: remove_blank_day)
      flash[:success] = "Product created"
    else
      flash[:failure] = "Product not created"
    end
    redirect_to root_path
  end

  def new
    @days = ["Everyday"] + Date::DAYNAMES

    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)
    flash[:success] = "Product updated"
    redirect_to products_path
  end

  def index
    @products = Product.base_products
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
    flash[:success] = "Product deleted"
  end

  def show
  end

  private

  def product_params
    params.require(:product).permit(:name, :theshold_to_order, :price, :unit_type, :desired_total, :days_to_order => [])
  end

  def remove_blank_day
    params[:product][:days_to_order] - [""]
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController

  def create
    @was_created = false
    @shopping_list = ShoppingList.find_or_create_by(order_id: current_order.id) do |s|
      @was_created = true
    end

    if @was_created
      current_order.update_attributes(shopping_list_id: @shopping_list.id)
      current_order.save
    end

    current_order.products.each_with_index do |p,idx|
      item = nil
      if @was_created
        item = @shopping_list.shopping_items.build
      else
        item = @shopping_list.shopping_items[idx]
      end

      item.set_shopping_item_attributes(p)
      if item.save
        # no problems
        item.update_attributes(shopping_list_id: @shopping_list.id)
      else
        raise "Error saving item: #{item.inspect}"
      end
    end

    redirect_to @shopping_list
  end

  def show
    @shopping_list = ShoppingList.find(params[:id])
    @current_order = current_order
    @shopping_items = @shopping_list.items_needed_to_order

    respond_to do |format|
      format.pdf do
        render pdf: "shop_list.pdf",
        template: "shopping_lists/show.pdf.erb",
        encoding: 'UTF-8',
        locals: { shopping_list: @shopping_list, current_order: @current_order, shopping_items: @shopping_items }
      end
      format.html
    end
  end

  def index
  end

  private

  def shopping_list_params
    params.require(:shopping_list)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if Order.exists?(id: session[:current_order_id])
      # nothing
    else
      session.delete(:current_order_id)
    end

    @api_response = Weather.lookup(28414042, Weather::Units::CELSIUS)

    @forecasts = @api_response.forecasts.first(5)
    @today = @api_response.forecasts.first(1)
    @forecasts = @forecasts - @today
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # parse in `created_at.strftime("%x")`
  def japanese_date_format(date)
    date = date.split('/').reverse!
    date[1], date[2] = date[2], date[1]
    s = date[0] << '/' << date[1] << '/' << date[2]
  end
end

app/views/layouts/_header.html.erb
<div class="ui top menu">
  <%= link_to root_path, class: 'item' do %>
    <%= t :unplan_ordering_system %>
  <% end %>

  <%= link_to new_order_path, class: 'item' do %>
    <%= t :new_order %>
  <% end %>

  <% if !session[:current_order_id].nil? %>
    <%= link_to order_path(Order.find(session[:current_order_id])), title: 'Current Order', class: 'item' do %>
      <%= t :current_order %>
    <% end %>
  <% end %>

  <div class="right menu">
    <%= link_to new_product_path, class: 'item' do %>
      <%= t :new_product %>
    <% end %>

    <%= link_to products_path, class: 'item' do %>
      <%= t :view_all_products %>
    <% end %>
    <div class="ui simple dropdown item">
      <div class="text"><%= t :language %></div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <%= link_to "English", { locale: 'en' }, class: 'item'%>
        <%= link_to "日本語", { locale: 'ja' }, class: 'item' %>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unplan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, maximum-scale=1, user-scalable=no" />
  </head>

  <%#= render('layouts/header') %>

  <p>
  <h1 class="ui centered dividing header">
    <%= link_to root_path do %><i class="home icon"></i><% end %>Unplan Ordering System
  </h1>

  <div class="ui grid">
    <div class="two wide column">

    </div>

    <div class="twelve wide column">
      <%= semantic_flash %>

      <body>
        <%= yield %>
      </body>
    </div>

    <div class="two wide column">

    </div>

  </div>
</html>

app/views/layouts/pdf.html.erb
<meta content="text/html; charset=utf-8" http-equiv="content-type">
<!-- show.pdf.erb -->
<%= yield %>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<h2><%= t :order_history %></h2>

<% @lists.each_with_index do |list,idx| %>
    <% if idx >= 0 %>
      <% @order = Order.find(list.order_id); @time = list.created_at %>
      <h5>Shopping List for <%= @time.strftime("%A") %>, <%= @time.strftime("%x") %>, <%= @time.strftime("%X") %> </h5>
      <%= render partial: 'shopping_lists/shopping_list', locals: { shopping_items: list.items_needed_to_order } %>
  <% end %>
<% end %>

<%= paginate @lists %>

app/views/orders/new.html.erb
<h3>製品追加</h3>

app/views/orders/show.html.erb
<h4>Update Order for <%= @order.created_at.strftime("%A") %>,
  <%= @order.created_at.strftime("%x") %> (<%= @order.created_at.strftime("%X") %>) </h4>

<%= semantic_form_for(@order, html: { class: 'ui form' }, remote: true) do |f| %>
  <div class="ui segment">
    <%= f.semantic_fields_for :products, @order_products do |p| %>

        <%= p.inputs do %>
        <div class="four fields">
          <%= p.input :name, input_html: { readonly: true }, wrapper_html: { class: 'three wide field'} %>
          <%= p.input :theshold_to_order, input_html: { readonly: true }, wrapper_html: { class: 'three wide field'} %>
          <%= p.input :desired_total, input_html: { readonly: true }, wrapper_html: { class: 'three wide field'} %>
          <%= p.input :in_stock, wrapper_html: { class: 'three wide field'} %>
        </div>
        <% end %>
        <br />
    <% end %>
  </div>
  <%= f.action :submit, data: { disable_with: 'Submitting...' }, button_html: { class: 'small right floated ui blue submit button' } %>
  <%= link_to orders_path, class: 'ui small right floated button' do %> <%= t :show_all_orders %> <% end %>
<% end %>

<%= semantic_form_for(@shopping_list) do |f| %>
  <%= f.action :submit, format: 'pdf',  data: { disable_with: 'Submitting...' }, button_html: { onclick: "submitter()", class: 'small left floated ui green submit button' }%>
<% end %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>

<%= semantic_form_for(@product, html: { class: 'ui form'}) do |f| %>
  <div class="ui segment">
    <%= f.inputs do %>
      <div class="five fields">
        <%= f.input :name, wrapper_html: { class: 'field' } %>
        <%= f.input :theshold_to_order, wrapper_html: { class:  'field' } %>
        <%= f.input :desired_total, wrapper_html: { class:  'field' } %>
        <%= f.input :price, wrapper_html: { class: 'field' } %>
        <%= f.input :unit_type, wrapper_html: { class: 'field' } %>
      </div>
      <div class="one field">
        <%= f.input :days_to_order,
            collection: ["Everyday"] + Date::DAYNAMES,
            wrapper_html: { class: 'three wide field'},
            input_html: { class: "ui selection dropdown", multiple: true }  %>
      </div>
    <% end %>
  </div>
  <br />
  <%= f.action :submit, button_html: { class: 'small right floated ui blue submit button' } %>
<% end %>

<script>
  reload();
</script>

app/views/products/index.html.erb
<h1>Existing Products</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Product</th>
      <th>Order Threshold</th>
      <th>Desired Total</th>
      <th>Price</th>
      <th>Unit Type</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |p| %>
      <tr>
        <td><%= p.name %></td>
        <td><%= p.theshold_to_order %></td>
        <td><%= p.desired_total %></td>
        <td><%= p.price %></td>
        <td><%= p.unit_type %></td>
        <td>
          <%= link_to product_path(p), method: :delete, data: { confirm: "Remove #{p.name} from system?"} do %>
            <i class="red remove icon"></i>
          <% end %>
          <%= link_to edit_product_path(p), title: 'Edit' do %>
            <i class="edit icon"></i>
          <% end %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/products/new.html.erb
<h1>Add a new product to orders</h1>

<%= semantic_form_for(@product, html: { class: 'ui form'}) do |f| %>
  <div class="ui segment">
    <%= f.inputs do %>
      <div class="five fields">
        <%= f.input :name, wrapper_html: { class: 'field' } %>
        <%= f.input :theshold_to_order, input_html: { value: number_with_precision(@product.theshold_to_order, precision: 2)}, wrapper_html: { class:  'three wide field' } %>
        <%= f.input :price, wrapper_html: { class: 'field' } %>
        <%= f.input :desired_total, wrapper_html: { class: 'field' } %>
        <%= f.input :unit_type, wrapper_html: { class: 'field' } %>
      </div>
      <div class="one field">
        <%= f.input :days_to_order,
            collection: ["Everyday"] + Date::DAYNAMES,
            wrapper_html: { class: 'three wide field'},
            input_html: { class: "ui selection dropdown", multiple: true },
            selected: "Everyday" %>
      </div>
    <% end %>
  </div>
  <br />
  <%= f.action :submit, data: { disable_with: 'Submitting...' }, button_html: { class: 'small right floated ui blue submit button' } %>
</div>
<% end %>

<script>
  reload();
</script>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/shopping_lists/_shopping_list.html.erb
<table class="ui blue stackable celled table">
  <thead>
    <tr>
      <th><%= t :product_name %></th>
      <th><%= t :cost_per_unit %></th>
      <th><%= t :total_units_needed %></th>
      <th><%= t :total_cost %></th>
    </tr>
  </thead>

  <tbody>
    <% shopping_items.each do |item| %>
      <tr>
        <td><%= item.item_name %></td>
        <td><%= item.item_cost %></td>
        <td><%= item.item_amount %></td>
        <td><%= item.total_cost %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th><%= t :total_cost %> <%= shopping_items.sum("total_cost")%></th>
    </tr>
  </tfoot>
</table>

app/views/shopping_lists/create.html.erb
<h1>ShoppingLists#create</h1>
<p>Find me in app/views/shopping_lists/create.html.erb</p>

app/views/shopping_lists/index.html.erb
<h1>ShoppingLists#index</h1>
<p>Find me in app/views/shopping_lists/index.html.erb</p>

app/views/shopping_lists/show.html.erb
<h4>Shopping List for <%= @current_order.created_at.strftime("%A") %>,
  <%= @current_order.created_at.strftime("%x") %>, <%= @current_order.created_at.strftime("%X") %> </h4>

<%= render partial: 'shopping_list', locals: { shopping_items: @shopping_items } %>

<%= link_to shopping_list_path(@shopping_list, format: :pdf), target: 'blank', class: 'ui right floated labeled icon button' do %>
  <i class="print icon"></i> <%= t :print_shopping_list %>
<% end %>

<%= link_to order_path(@current_order), class: 'ui left floated green button' do %>
  Return to current order
<% end %>

app/views/shopping_lists/show.pdf.erb
<h2>Unplan Shopping List for <%= current_order.created_at.strftime("%A") %>,
  <%= current_order.created_at.strftime("%x") %> </h2>


<table class="ui blue celled table">
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Cost per unit</th>
      <th>Total units needed</th>
      <th>Total cost</th>
    </tr>
  </thead>

  <tbody>
    <% shopping_items.each do |item| %>
      <tr>
        <td><%= item.item_name %></td>
        <td><%= item.item_cost %></td>
        <td><%= item.item_amount %></td>
        <td><%= item.total_cost %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th>Total: <%= shopping_items.sum("total_cost")%></th>
    </tr>
  </tfoot>
</table>

app/views/static_pages/_forecast.html.erb
<div class="ui fluid card">
  <div class="content">
    <img src="<%= api_response.image.url %>" class="right floated mini ui image">
    <div class="header">
      <%= t today.day.to_sym %>
    </div>
    <div class="meta"><%= t today.text.gsub(" ", "_").to_sym %></div>
    <div class="description">
      <div class="ui two column centered grid">
        <div class="column">
          <div class="ui red statistic">
            <div class="value"><%= today.high %></div>
            <div class="label"><%= t :maximum_temp %></div>
          </div>
        </div>
        <div class="column">
          <div class="ui blue statistic">
            <div class="value"><%= today.low %></div>
            <div class="label"><%= t :minimum_temp %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<!-- current order -->
<div class="ui stackable two column grid">
  <div class="column">
      <div class="ui centered fluid card">
        <div class="content">
          <div class="header">
            <%= t :current_order %>
          </div>
          <div class="meta"><!-- extras? --></div>
          <div class="description">
            <%= t :current_order_description %>
          </div>
        </div>
        <div class="extra content">
          <div class="two ui buttons">

            <%= link_to new_order_path, title: "New Order", class: 'ui basic blue button' do %>
              <%= t :create_new_order %>
            <% end %>
            <% if !session[:current_order_id].nil? %>
              <%= link_to order_path(Order.find(session[:current_order_id])), title: 'Current Order', class: 'ui basic green button' do %>
                Update Order [<%= japanese_date_format(Order.find(session[:current_order_id]).created_at.strftime("%x")) %>]
              <% end %>
            <% end %>

            <%#= link_to shopping_list_path(Order.find(session[:current_order_id])), title: 'Shopping List', class: 'ui basic blue button' do %>
              <%#= t :get_shopping_list %>
            <%# end %>

          </div>
        </div>
      </div>
  </div>

  <div class="column"> <!-- weather -->
    <div class="ui fluid card">
      <div class="content">
        <img src="<%= @api_response.image.url %>" class="right floated mini ui image">
        <div class="header">
          <%= t @today.first.day.to_sym %>
        </div>
        <div class="meta"><%= t @today.first.text.gsub(" ", "_").to_sym %></div>
        <div class="description">
          <div class="ui two column centered grid">
            <div class="column">
              <div class="ui red statistic">
                <div class="value"><%= @today.first.high %></div>
                <div class="label"><%= t :maximum_temp %></div>
              </div>
            </div>
            <div class="column">
              <div class="ui blue statistic">
                <div class="value"><%= @today.first.low %></div>
                <div class="label"><%= t :minimum_temp %></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div> <!-- end second column -->
</div> <!-- end grid -->
<div class="ui divider"></div>

<h4 class="ui center aligned icon header">
  <i class="settings icon"></i>
  <%= t :options %>
  <br />
</h4>
<!-- new order etc -->
<div class="ui three stackable cards">
  <div class="ui card">
    <div class="content">
      <div class="header">
        <%= t :history %>
      </div>
      <div class="meta"><!-- extras? --></div>
      <div class="description">
        <%= t :history_description %>
      </div>
    </div>
    <div class="extra content">
      <div class="two ui buttons">
        <%= link_to orders_path, class: 'ui basic blue button' do %>
          <%= t :show_all_orders %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="ui card">
    <div class="content">
      <div class="header">
        <%= t :products %>
      </div>
      <div class="meta"><!-- extras? --></div>
      <div class="description">
        <%= t :product_description %>
      </div>
    </div>
    <div class="extra content">
      <div class="two ui buttons">
        <%= link_to new_product_path, class: 'ui basic green button' do %>
          <%= t :create_new_products %>
        <% end %>

        <%= link_to products_path, class: 'ui basic blue button' do %>
          <%= t :show_all_products %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="ui card">
    <div class="content">
      <div class="header">
        <%= t :language %>
      </div>
      <div class="meta"><!-- extras? --></div>
      <div class="description">
        <%= t :language_description %>
      </div>
    </div>
    <div class="extra content">
      <div class="two ui buttons">
        <%= link_to "English", { locale: 'en' }, class: "ui basic yellow button" %>
        <%= link_to "日本語", { locale: 'ja' }, class: 'ui basic red button' %>
      </div>
    </div>
  </div>
</div>

<div class="ui divider"></div>
<!-- weather -->
<h4 class="ui center aligned icon header">
  <i class="sun icon"></i>
  <%= t :weather_forecast %> <%= "(#{t @api_response.location.city.to_sym}, #{t @api_response.location.country.to_sym})"%>
</h4>

<div class="ui four stackable cards">

  <% @forecasts.each do |forecast| %>
    <%= render partial: 'forecast', locals: { today: forecast, api_response: @api_response } %>
  <% end %>
</div>